version: '3'

services:
  wordpress:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: wordpress
    ports:
      - "80:80"
    environment:
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_USER: wordpress
      WORDPRESS_DB_PASSWORD: wordpress_password
      WORDPRESS_DB_NAME: wordpress
    depends_on:
      - db
    networks:
      - wordpress-network
    restart: always

  db:
    image: mysql:8.0
    container_name: wordpress_db
    command: 
      - --general-log=1
      - --general-log-file=/var/log/mysql/query.log
      - --log-output=FILE
    environment:
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: wordpress_password
      MYSQL_ROOT_PASSWORD: root_password
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - wordpress-network
    restart: always

networks:
  wordpress-network:
    driver: bridge

volumes:
  db_data: